# Generated by Django 5.2.11 on 2026-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0002_alter_profil_options_alter_profildurum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profildurum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
